### ISSUE TITLE
你好，想请问你使用MARLLIB库进行异构多智能体解决了吗？

### ISSUE THREAD

**Issue by buwenliu** [Miracle1207/AI_Economic_Database#1]
我不知道该如何创建一个自定义的异构多智能体环境能不能请教你一下，万分感谢
`REGISTRY = {}
policy_mapping_dict = {
    "all_scenario": {
        "description": "aquacrop env",
        "team_prefix": ("timer_", "amount_"),
        "all_agents_one_policy": True,
        "one_agent_one_policy": True,
    },
}

class RLlibCrop(MultiAgentEnv):

    def __init__(self, env_config):
        map = env_config["map_name"]
        env_config.pop("map_name", None)
        env = REGISTRY[map](**env_config)

        env = ss.pad_observations_v0(env)
        env = ss.pad_action_space_v0(env)

        self.env = ParallelPettingZooEnv(env)

        self.max_obs_dim = 12  # 观察空间的最大维度
        self.max_act_dim = 14  # 动作空间的最大维度
        self.action_time = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
        self.action_depths = [0, 0, 0, 0, 2.5, 5, 7.5, 10, 12.5, 15, 17.5, 20, 22.5, 25]
        self.share_observation_space = [spaces.Box(-np.inf, np.inf, (20,))]
        # self.observation_space = [spaces.Box(-np.inf, np.inf, (12,)),
        #                           spaces.Box(-np.inf, np.inf, (12,))]
        # self.action_space = [spaces.Discrete(14),
        #                      spaces.Discrete(14)]
        # self.agents = {"irrigation_timer1", "irrigation_amount"}
        self.action_space = self.env.action_space
        self.observation_space = GymDict({"obs": Box(
            low=-100.0,
            high=100.0,
            shape=(self.env.observation_space.shape[0],),
            dtype=self.env.observation_space.dtype)})
        self.agents = self.env.agents

        self.num_agents = len(self.agents)
        env_config["map_name"] = map
        self.env_config = env_config
`
`if __name__ == '__main__':
    # register new env
    ENV_REGISTRY["crop"] = RLlibCrop
    # initialize env
    env = marl.make_env(environment_name="crop", map_name="crop")
    # pick mappo algorithms
    mappo = marl.algos.mappo(hyperparam_source="test")
    # customize model
    model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-128"})
    # start learning
    mappo.fit(env, model, stop={'episode_reward_mean': 2000, 'timesteps_total': 10000000}, local_mode=True, num_gpus=1,
              num_workers=2, share_policy='all', checkpoint_freq=50)
`
报了以下错误：| crop               | Ready          | Null                                                                                                                                                                    | envs/base_env/config/crop.yaml               | envs/base_env/crop.py               |
+--------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
Traceback (most recent call last):
  File "C:\Users\13166\Desktop\marllib\envs\base_env\crop.py", line 462, in <module>
    env = marl.make_env(environment_name="crop", map_name="crop")
  File "C:\Users\13166\Desktop\marllib\marl\__init__.py", line 151, in make_env
    env = ENV_REGISTRY[env_config["env"]](env_config["env_args"])
  File "C:\Users\13166\Desktop\marllib\envs\base_env\crop.py", line 124, in __init__
    env = REGISTRY[map](**env_config)
KeyError: 'crop'

**Comment by buwenliu** [comment]
我之前使用过HARL库，可以成功进行异构多智能体训练，但是效果不太满意，想试试Marllib这个库

**Comment by Miracle1207** [comment]
也许你可以参考 TaxAI https://github.com/jidiai/TaxAI/    ，这是一个异质多智能体的环境。我曾经关注过Marllib ，但最后没有使用这个库

**Comment by buwenliu** [comment]
好的，谢谢您
